sudo: false
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
notifications:
  email: false
script:
  - yarn run test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
